### PR TITLE
Create CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by rainleander**
## Description

Our repositories should be the example from which adjacent, competing, projects look for inspiration.

Each repository should not look entirely different from other repositories in the ecosystem, having a different layout, a different testing model, or a different logging model, for example, without reason or recommendation from the subject matter experts from the community.

We should share our improvements with each ecosystem while seeking and respecting the feedback of these communities.

Whether or not strict guidelines have been provided for the project type, our repositories should ensure that the same components are offered across the board. How these components are provided may vary, based on the conventions of the project type. GitHub provides general guidance on this which they have integrated into their user experience.

#75

### CODE REVIEW

**Comment by mmlb** [comment]
@rainleander missed DCO

**Comment by rainleander** [comment]
My B! Fixed.

Signed-off-by: K Rain Leander <rainleander@users.noreply.github.com>

**Comment by mmlb** [comment]
@rainleander this is actually going to go into .github and this file will basically just be a link to that right?

**Comment by jacobweinstock** [comment]
duplicate of https://github.com/tinkerbell/boots/pull/162

**Pull request closed without merging**
