### PR TITLE
Return a nice error when DATA_MODEL_VERSION not set

### PR DESCRIPTION
**Pull request by justinsb**
Otherwise we panic on the first DHCP request.

### CODE REVIEW

**Review by chrisdoherty4 — DISMISSED** [review]
Thanks @justinsb.

**Comment by chrisdoherty4** [comment]
There's an ineffectual assignment on l.225.

Change:
```
var wf client.WorkflowFinder = &client.NoOpWorkflowFinder{}
```

To:
```
var wf client.WorkflowFinder
```

**Comment by justinsb** [comment]
Thanks - fixed that up!

(I'm going through this and starting off by fixing small things I find, the project looks really interesting :-) )

**Comment by chrisdoherty4** [comment]
> Thanks - fixed that up!
> 
> 
> 
> (I'm going through this and starting off by fixing small things I find, the project looks really interesting :-) )

That's awesome and we really appreciate it.

If you're interested in high level roadmap items check out the [roadmap repo](https://github.com/tinkerbell/roadmap) and its associated project.

**Review by chrisdoherty4 — APPROVED** [review]

**Pull request merged**
