### PR TITLE
Allow PXE booting regardless of an existing workflow:

### PR DESCRIPTION
**Pull request by jacobweinstock**
## Description

Currently, a machine will only PXE boot if it has an existing tink workflow.
To do any other type of PXE boot (custom ipxe, osie, hook, etc) you have to create a workflow that will never actually be run.
This commit allows machines to PXE into OSIE, hook, OSIE alternative, custom ipxe, etc without needing a workflow.
PXE booting will be gated by the tink hardware data field: `network.interfaces[].netboot.allow_pxe`

## Why is this needed

Allows machines to PXE boot without a workflow.

Fixes: https://github.com/tinkerbell/boots/issues/114

## How Has This Been Tested?

I built the boots image and ran it with the vagrant sandbox locally to test. It worked as intended there. 

## How are existing users impacted? What migration steps/scripts do we need?

no migrations.

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [ ] added unit or e2e tests
- [ ] provided instructions on how to upgrade

### CODE REVIEW

**Review by gianarb — APPROVED** [review]
Thank you for taking care of this!!

**Comment by gianarb** [comment]
Now that I am thinking about it @jacobweinstock do you mind to figure out and add tests for this? not sure about the status of the test suite but @mmlb knows more I suppose

**Comment by mmlb** [comment]
Hmm the issue with this atm is that there's nothing to turn it off once a workflow is done. This is likely to be a problem when machines are set to boot from nic by default, which is probably the case for NUCs/machines w/o a BMC, or even servers with PXE boot as default because of fw issues (some EM machines are like this)

**Review by markyjackson-taulia — APPROVED** [review]

**Comment by mmlb** [comment]
We don't really have a good story for messing with hw data. Should tink-(worker/server) disable allow_pxe if the workflow is finished? Is this another case for "builtin tink-worker actions"? Do we build something via ephemeral_data to signal this?

**Comment by jacobweinstock** [comment]
> Hmm the issue with this atm is that there's nothing to turn it off once a workflow is done. This is likely to be a problem when machines are set to boot from nic by default, which is probably the case for NUCs/machines w/o a BMC, or even servers with PXE boot as default because of fw issues (some EM machines are like this)

Setting this stops boots from handing out pxe stuff.
network.interfaces[].netboot.allow_pxe=false

Also at the moment, a provision is only started when some external source sets a machine to pxe boot and restarts it. This approach relies on this same idea. If a machine shouldn't be pxe booted then it shouldn't set itself to pxe boot.

Whether tink controls the setting of boot devices and power cycling or not doesn't feel like it should matter. If a machine is set to pxe, boots should pxe.

What is pxe'd is a bit different. Is it a discovery OS, OSIE and a workflow, a custom ipxe script, a live CD? I feel that what is pxe'd will most likely be very specific to the environment where tink is deployed. Those business rules should be flexible and accommodate all users. Encoding those in boots doesn't feel like the correct approach.

The change at least allows machines to not have to create useless workflows just to pxe. It creates more flexibility by giving more control back to the environment.

**Comment by gianarb** [comment]
I agree with @jacobweinstock here. We have a field already set that pilots if a machine should boot or not via PXE boot `network.interfaces[].netboot.allow_pxe=false`. The fact that you have to create a workflow is not documented and counterintuitive.

> Hmm the issue with this atm is that there's nothing to turn it off once a workflow is done. This is likely to be a problem when machines are set to boot from nic by default, which is probably the case for NUCs/machines w/o a BMC

I think the power cycle issue should not prevent us to make this change. It is an issue on its own. For example, I have 10 NUC and I have recently figured out how I can hook an RPI to them to pilot the power lifecycle.

We have also the ongoing effort to support reboot, power off in tink-worker, and hook. So, it is an issue on its own.

**Comment by mmlb** [comment]
SGTM. Internally we have a separate service that will update the allow_pxe field so we'd be fine. I wanted to make sure we don't make it harder for other members of the community to mess with tinkerbell.

> I agree with @jacobweinstock here. We have a field already set that pilots if a machine should boot or not via PXE boot `network.interfaces[].netboot.allow_pxe=false`. The fact that you have to create a workflow is not documented and counterintuitive. I opened this issue because during my experiments with NUCs I found that not an ideal behaviour.
> 
Also agree with this.

> > Hmm the issue with this atm is that there's nothing to turn it off once a workflow is done. This is likely to be a problem when machines are set to boot from nic by default, which is probably the case for NUCs/machines w/o a BMC
> 
> I think the power cycle issue should not prevent us to make this change. It is an issue on its own. For example, I have 10 NUC and I have recently figured out how I can hook an RPI to them to pilot the power lifecycle.

But that doesn't address what I brought up. Your NUCs are set to PXE boot by default right? Your RPi doesn't configure that on them does it?

I think we should definitely merge this but I'm also trying to figure out if we can have a nice way to not have to leave it up to docs that you'd want to go back and edit the hw and change the allow_pxe: false after done with a workflow.

**Comment by mmlb** [comment]
Maybe we break this off into a discussion for the last bit I mentioned.

**Review by mmlb — APPROVED** [review]

**Pull request merged**
