### PR TITLE
ci: Run builds on our self hosted builders

### PR DESCRIPTION
**Pull request by mmlb**
## Description

Run ci builds on our self hosted, bare metal runners.

## Why is this needed

Faster builds/results especially for the iPXE builds.

## How Has This Been Tested?

GitHub Actions

## How are existing users impacted? What migration steps/scripts do we need?

Faster test cycles

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [ ] added unit or e2e tests
- [ ] provided instructions on how to upgrade

### CODE REVIEW

**Comment by mmlb** [comment]
depends on getting git-lfs in the runners, either via https://github.com/tinkerbell/infrastructure/pull/9 or by installing locally.

**Comment by tstromberg** [comment]
The `Install nix` test is failing at `checkExecSyncError` - can you get this cleared up?

**Comment by mmlb** [comment]
Yep, I believe we now have builders with nix preinstalled so no need for that bit.

**Comment by mmlb** [comment]
looks like self-hosted runners now have nix :raised_hands: so will need to mess with this to work around some of the self-hosted GHA differences.

**Comment by mmlb** [comment]
@gianarb/@tstromberg ready for re-review!

**Review by matoszz — APPROVED** [review]
a slight nit, but I would suggest splitting out the go related tasks into it's own actions workflow so that you only run it when the go files are modified, otherwise you're doing a lot of setup + re-running steps unnecessarily

**Comment by mmlb** [comment]
> a slight nit, but I would suggest splitting out the go related tasks into it's own actions workflow so that you only run it when the go files are modified, otherwise you're doing a lot of setup + re-running steps unnecessarily

meh idk if its worth it since most of the time the go files are in fact being touched.

**Pull request merged**
