### PR TITLE
Unexport CreateFromIP

### PR DESCRIPTION
**Pull request by nshalman**
## Description

Cleanup of #120 by @ilmanzo. There may be some additional work that can/should be completed in this PR as described in #118 but I haven't done it yet.

Thanks again to @ilmanzo for the first pass of this!

## Why is this needed

Fixes: #118

## How Has This Been Tested?

```make test```

### CODE REVIEW

**Comment by nshalman** [comment]
@ilmanzo are you comfortable with how I've credited your work in this PR?

**Comment by mmlb** [comment]
I'd prefer you squash your commit into the previous so we don't introduce a non-bisectable commit.

**Review by jacobweinstock — DISMISSED** [review]

**Comment by nshalman** [comment]
This branch also doesn't yet ([link](https://github.com/tinkerbell/boots/issues/118#issue-784415357))
> just drop tftpClientIP

But I will also squash stuff in the meantime.

**Comment by nshalman** [comment]
I haven't had time to look back into this, but it's still something I can work on at some point.

**Comment by nshalman** [comment]
Looks like I need to rebase.

**Pull request closed without merging**
