### PR TITLE
Reduce tftp block size

### PR DESCRIPTION
**Pull request by mmlb**

### CODE REVIEW

**Comment by pereztr5** [comment]
Jira: [ENG-6765](https://packet.atlassian.net/browse/ENG-6765)

**Comment by pereztr5** [comment]
@mmlb I think since we set the packet size to `1468` it collides with what I just found as the packet size of `1450` in it's routing rules.
```
root@edge-prod-ny5-06:~# ip r
default via 136.144.50.150 dev bond0 onlink
10.66.1.134/31 dev bond0 proto kernel scope link src 10.66.1.135
136.144.50.150/31 dev bond0 proto kernel scope link src 136.144.50.151
169.254.255.1 via 10.66.1.134 dev bond0
169.254.255.2 via 10.66.1.134 dev bond0
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown
192.168.0.0/24 via 192.168.3.72 dev cilium_host src 192.168.3.72 mtu 1450
192.168.1.0/24 via 192.168.3.72 dev cilium_host src 192.168.3.72 mtu 1450
192.168.2.0/24 via 192.168.3.72 dev cilium_host src 192.168.3.72 mtu 1450
192.168.3.0/24 via 192.168.3.72 dev cilium_host src 192.168.3.72 mtu 1450
192.168.3.72 dev cilium_host scope link
192.168.4.0/24 via 192.168.3.72 dev cilium_host src 192.168.3.72 mtu 1450
```

**Comment by mikemrm** [comment]
@mmlb can we close this now? Believe this fix was resolve with https://github.com/tinkerbell/boots/pull/70

**Comment by mmlb** [comment]
indeed

**Pull request closed without merging**
